### ISSUE TITLE
Decide where mixer output for chroots should go

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#103]
```
<pmccarty> my idea from a few months ago was to create a "meta" directory instead
<pmccarty> and rename "image" to "chroots"
<pmccarty> so meta would live alongside chroots
<pmccarty> packages-* and *-includes would be installed in meta/
<mrsj> I think we need to have a meeting and decide what the input and output of updates should look like
<mrsj> instead of just moving things around whenever we don't like the way it looks
```

The outputs include:
- files-* files (apparently not used)
- packages-BUNDLE files that list all the packages present in a BUNDLE
- BUNDLE-includes files that list the bundles included by BUNDLE

We also have two configuration files used to communicate information to the next step (build update)
- server.ini
- groups.ini

**Comment by tmarcu** [comment]
I like the idea of having a /chroots/30/build-data/ directory to store the package and bundle information files in; something along those lines at least so it's intuitive for me to look in there when I want to find that info. I think we have to decide on the config type we want to use (TOML) and change groups.ini -> bundles.toml and get rid of server.ini since builder.conf hosts ~all that info realistically.
