### ISSUE TITLE
mixer init neither fails or do the work when called repeatedly

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#125]
When calling mixer init, and then calling it again, it does some of the work, but not all, but doesn't fail, which could be confusing. 

I think we should fail at init if we find that the directory was already initialized. Usually this happens either by mistake or by not knowing how to bump to a new version, so could be useful to add some information on how to do that in the error message.

Section below shows examples.

```
$ ls
$ mixer init --clear-version 20600 --mix-version 10
Creating new builder.conf configuration file...
Adding bundle "os-core-update"
Adding bundle "kernel-native"
Adding bundle "os-core"
Adding bundle "bootloader"
Initialized empty Git repository in /home/c/src/mix3/mix-bundles/.git/
[master (root-commit) 594f30b] Initial mix version 10 from upstream version 20600
 4 files changed, 76 insertions(+)
 create mode 100644 bootloader
 create mode 100644 kernel-native
 create mode 100644 os-core
 create mode 100644 os-core-update
$ mixer init --clear-version 20600 --mix-version 20
$ mixer init --clear-version 20610 --mix-version 20
$ cat .mixversion 
20   # Added a fake newline here for clarity.
$ mixer init --clear-version 20610 --mix-version 30 --local-rpms
$ cat .mixversion 
30   # Added a fake newline here for clarity.
$ cat .clearversion 
20610     # Added a fake newline here for clarity.
$ ls
builder.conf  mix-bundles
$ git -C mix-bundles/ shortlog
Caio Marcelo de Oliveira Filho (1):
      Initial mix version 10 from upstream version 20600
$ grep RPM builder.conf
$ 
```

**Comment by rchiossi** [comment]
I agree. Originally there where more informative output regarding what was being done and what was being skipped, but there was a request to reduce verbosity, so they were gone in the version that got integrated.

The main reason why init doesn't fail when the new steps run (builder.conf creation and --local-rpms) is because it was designed to not chance the workflow of the existing init-mix command.

Now that init is its own new thing, I'm in favor of changing it to fail in those situations, but I'd like to have some more information on what are the current use cases of mixer init, in particular the legacy ones. Is bumping the version the only other use case for mixer init? @tmarcu do you have a better insight on the subject?

**Comment by kevincwells** [comment]
It's a good idea to have a more clearly-defined (and clearly-communicated) scope of what `init` is supposed to do for a user, and under what circumstances. The approach so far has been to try to do things if they haven't already been done, and no-op if they have. This allows for a very fine-grained control -- you can do any or all of the steps yourself, and `init` will do the rest.  (The fact that it overwrites `.clearversion` and `.mixversion` instead of no-op'ing if they exist, however, is an inconsistent mistake. And it leads to people using `init` to "set the mix version", which is not what `init` is for at all.)

Having `init` return failure if it thinks the directory has already been initialized is one way of communicating to the user when things will and won't happen and what `init` is for. On one end of the spectrum, we could convert any of the "instead no-op" cases to failures. Then it's all-or-nothing - you're either using `init` to set things up, or you're doing it yourself. On the other end of the spectrum, if we want to preserve more granular initialization, init could only return failure if _everything_ no-op'd.

The above illustrates that we need to be a little careful about how we define how it knows "if the directory has already been initialized".

It "can't" be the existence of `builder.conf`.  As mentioned in #124, right now the existence of a `builder.conf` (or passing one in) doesn't stop `init`, because `builder.conf` tells it where to do its other work (creating the version files, etc.). Similarly, the existence of certain directories (`mix-bundles`, `VERSIONS_DIR`, etc) shouldn't kill it, because the conf could point anywhere, and it's the files inside these directories that matter.

**Comment by cmarcelo** [comment]
I had in mind the smaller scope init that just creates the workdir for the first time (see also my suggestion about putting the RPM commented in the config). For which "builder.conf" exists would be an OK test for init bailing out.

If init also "fill in new things", then the story is different of course.

In both cases the existing behavior is wrong.

**Comment by cmarcelo** [comment]
> but I'd like to have some more information on what are the current use cases of mixer init, in particular the legacy ones.

I don't think we have users of this command yet, IMHO you don't need to worry about legacy users here.

The use case I always had in mind was: "hey I want to create a mix, can you create all that configuration for me".

**Comment by rchiossi** [comment]
'init-mix',  the predecessor of 'init',  has been around since before we joined the project so I expect it to have user. Also, it is in the official guide.

**Comment by cmarcelo** [comment]
See also: https://github.com/clearlinux/swupd-client/pull/385

**Comment by tmarcu** [comment]
You should not fail if you have already initialized a directory...in another program:
```
tmarcu@dev ~/test $ git init .
Initialized empty Git repository in /home/tmarcu/test/.git/
tmarcu@dev ~/test $ git init .
Reinitialized existing Git repository in /home/tmarcu/test/.git/
```
At most no-op and print something like this. It currently is still being used to update versions, for which there should arguably be a different method.

**Comment by cmarcelo** [comment]
I still think it needs either documentation or the command should be fixed to do something else in those cases.
