### ISSUE TITLE
Enumerate then contain/eliminate the places we need root

### ISSUE THREAD

**Issue by cmarcelo** [clearlinux/mixer-tools#158]
From @icarus-sparry comment https://github.com/clearlinux/mixer-tools/pull/155#discussion_r167036767: _We ought to see exactly what wants 'root', and see if we can eliminate the need as a medium term goal._

Created this ticket to try at least get some sense of the amount of work we have to do. Note that if we have cases we do want to use root, it would be nice to "contain" them, so that other functionality can run as the regular user. The more we make "mixer" user-friendly (by creating or updating files for me), the more problematic become it creating some files as root as I create other files with my user.

Non-exhaustive list of places we currently need root permissions:

- When creating the chroots we install RPMs and then expect the filesystem to look exactly like the final filesystem. I'm not sure about the status of running the dnf/yum without root, but I guess that's workable. There were previously suggested solutions for final state of the files: accept a list of files/metadata, plus the file contents. Another idea I've seen in mkosi, optionally accept a chroot tar file in place of a chroot directory: the tarfile contains the permissions, and is something one could easily create from inside a fakeroot execution.

- Image creation needs privileges to mount loopback devices.

**Comment by icarus-sparry** [comment]
The yocto project use 'fakeroot' to create filesystems that appear to look exactly like the final filesystems but with needing root at all. It works by injecting extra libraries via LD_LIBRARY_PATH.

I think longer term we want to move away from using the filesystem as a simple database to something a little bit faster, there are issues where yum slows everything down massively due to excessive calls to sync. 

Of course the usual way to boot a linux system with an initial ramdisk these days is to give the ramdisk as a cpio archive, so lots of precedent for the mkosi approach mentioned.

**Comment by tmarcu** [comment]
This will be affected by https://github.com/clearlinux/mixer-tools/issues/203

**Comment by tmarcu** [comment]
Mixer runs in container by default not requiring root.
