### ISSUE TITLE
[Builder] BUNDLE_DIR vs [Mixer] LOCAL_BUNDLE_DIR

### ISSUE THREAD

**Issue by mbelluzzo** [clearlinux/mixer-tools#268]
Is [Builder] BUNDLE_DIR still used at all? When moving from an older mixer release to 4.3.3, it looks like mix-bundles folder is useless.

If it isn't required anymore, can mixer stop to create this entry on builder.conf and avoid confusion?

If it is, what is the current usage?

**Comment by rchiossi** [comment]
`The BUNDLE_DIR variable sets the path where mixer temporarily stores the bundle definition files while building chroots. Only the legacy chroot-builder uses this path. `

You are right. Since we just removed the old chroots, this is not needed anymore. Still, I'm working on some sort of versioning system for builder.conf to handle compatibility between versions, so I prefer to imbue this change once the versioning is out.

**Comment by rchiossi** [comment]
This variable only existed in the old config. Since mixer 5.2.0, mixer only uses new config which does not contain this variable.
