### ISSUE TITLE
Mixer build delta-packs won't work after a build all

### ISSUE THREAD

**Issue by otaviobp** [clearlinux/mixer-tools#445]
Running mixer commands in this order will fail:

    $ sudo mixer build all
    $ sudo mixer build delta-packs --previous-versions=1

mixer build all updates mixversion and this information is used by delta-packs to check what's the current version to be used.

If build bundles and build update is used, delta-packs works fine because mixversion isn't updated:

    $ sudo mixer build bundles
    $ sudo mixer build update
    $ sudo mixer build delta-packs --previous-versions=1

**Comment by chivakker** [comment]
@tmarcu this seems to be an actual bug, rather than an enhancement.

As stated by @otaviobp 

$ sudo mixer build all
$ sudo mixer build delta-packs --previous-version=1

it fails to find a Manifest for the next version?

i.e. my last version is 640 (this is deployed on my target system)

$ sudo mixer build delta-packs --native --previous-versions 1
ERROR: couldn't find manifest of target version: open <redacted>/mix/update/www/650/Manifest.MoM: no such file or directory

while this command will just work

 sudo mixer build delta-packs --from 630 --to 640 --native
Using 4 workers
=> CREATE DELTA PACKS
Creating delta packs from 630 to 640
  Creating delta pack for bundle "os-core" from 630 to 640
  Creating delta pack for bundle "os-core-update-index" from 630 to 640
    Fullfiles in pack: 0
    Deltas in pack: 1
    Fullfiles in pack: 2
    Deltas in pack: 1

TIMINGS
  CREATE DELTA PACKS 202ms
TOTAL: 202ms

can $ sudo mixer build all build also delta-packs.  User wants fastest updates
