### ISSUE TITLE
Remove support for running mixer commands inside container

### ISSUE THREAD

**Issue by jwakre** [clearlinux/mixer-tools#528]
Mixer is no longer required to run commands inside of a container and removing this feature reduces mixer's complexity. After this change, mixer would no longer need the '--native' flag because it will always run natively.

**Comment by rchiossi** [comment]
In order to remove docker, we will need to check all formats that had this feature available for auto-bump (24, 25, and 26) and make sure mixer can do a proper bump. 25 to 26 should be good to go, but we need to check the changes from 24 to 25.

**Comment by jwakre** [comment]
I don't think removing Docker would impact specific formats, but an incorrect implementation could break format bumps in general. Just to be safe, I ran format bumps from 24->25 and did not experience any problems.

**Comment by rchiossi** [comment]
The reason I mentioned the bump from 24 to 25 is because right now mixer is able to work on those formats by downloading the correct image with the correct mixer version and working inside docker. In order to keep backwards compatibility, the new mixer has to be able to do it as well.

**Comment by jwakre** [comment]
My PR completely removes support for running inside of a container, so older formats would not run in a container. I don't see why older formats would be required to be run inside a container. Executing commands in a container shouldn't modify how manifests are formatted and native builds should have been supported.

**Comment by rchiossi** [comment]
The only reason containers exists in the first place is to add support for older formats. This way mixer could focus only in the current format and download older versions of itself to generate content for older format. This means that up until support for format 26 was added, in paper mixer was unable to process older formats. If it works, it is by pure chance.

**Comment by jwakre** [comment]
In  that case, I see the format issue now.

**Comment by rchiossi** [comment]
This feature was introduced to handle format bumps. When doing a bump, you need to generate two sets of metadata: One with the tooling for the old format and one with the tooling of the new format. As such, mixer would download two docker images, one with the latest mixer version for the old format and one with the latest mixer version for the new format. Then it would generate the update metadata twice, once with each downloaded version. For a format bump without docker, like what devops do, they actually had to manually download two versions of mixer and manually swap versions to generate that metadata.

Format 26 was the first format that didn't require this change since the mixer binary was able to generate metadata for both format 25 and 26, removing the need to manually swap binaries during format bumps.

Besides its use for format bumps, using docker had the advantage of setting an unified build environment, which made it easier to run mixes on other systems other than clear and that is why it was made default. Its original design was solely focused on supporting older formats for bumps though.

**Comment by jwakre** [comment]
Based on our conversation, I can re-define this enhancement as follows:

* formats >= 25, build natively on host always
* formats < 25 build in container by default and natively when passed --native flag

**Comment by gtkramer** [comment]
Removing the docker component to mixer would help improve the CLI in response to #627 by removing the need for the `--native` flag.

**Comment by rchiossi** [comment]
We don't have any blocker to proceed with this now. Support for format 25 and below is not something we need to worry anymore and for users using docker for compatibility only, we should point them to mixer-ci image instead.

**Comment by reaganlo** [comment]
Fixed in v6.0.0
