### ISSUE TITLE
Previous data that needs to exist to generate new updates

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#542]
I am trying to debug some issues in our build system and have stumbled upon some problems with generating updates when the full chroot for a previous version does not exist. Can someone explain what **must** be kept between updates to be able to generate further updates. I was under the impression it was only the **www** directory that had to be kept but I am seeing failures because the full chroot for previous versions is missing from the **image** directory.

The scenario I am trying here was to generate an update from 2 to 3 with the version 1 directory deleted from the update/image directory. This failed and I assumed it was because `--previous-versions` was set to 3. So I set it to 1 so that it should only generate delta for 2 -> 3. This also failed and the result is the log: [swupd-error.txt](https://github.com/clearlinux/mixer-tools/files/2838869/swupd-error.txt)

**Comment by rchiossi** [comment]
Suppose a package was added to your mix in version 10. If there wasnt any change to it when you generate version 20, the manifest of that package will point to version 10. This way, when you generate version 30, if again there was no change to that package, it will still reference version 10, which mean mixer will look for the files that are no longer there.

In order to safely remove older files, you need to create a new mix that is also a min-version. That creates a checkpoint and guarantees that any versions that comes after it will not reference any version that came before the most recent min-version. Check the `--min-version` flag for `mixer build` commands.

There is already an issue that dicusses further improvements to space cleanup. Check #457 for more info.

**Comment by aaronovz1** [comment]
Thanks. That is good information to know. In my scenario we had a build system issue where version 1 directory/chroot got deleted. The only way I could get version 3 to generate was to set `--previous-versions` to zero. I assume this just means no deltas and files will be downloaded from full packs? Is this really the only way forward? Can a checkpoint be made from this point forward so further versions won't rely on version 1?
