### ISSUE TITLE
Feature: Bundle delete command

### ISSUE THREAD

**Issue by kevincwells** [clearlinux/mixer-tools#56]
# New Feature
Add a command (`mixer bundle delete`) that removes bundle(s) from your mix.

# Notes
- Counterpart to `mixer bundle add`
- Removes the bundle from the Mix Bundle List (see #55)
- Optionally (`--local`) also removes the bundle definition file from the `local-bundles` directory, if it exists.

**Comment by cmarcelo** [comment]
> Attempts to handle automatically removing bundles included by the removed bundle, too.

I don't get this feature. Is it to manipulate the mix bundle list, local-bundle directory or both?

If the bundle is listed in the mix bundle list, we should not remove since we might have added it for other reasons. If the bundle is not listed there and it was just part of the mix because something else was deleted, it will go away.

**Comment by kevincwells** [comment]
@cmarcelo Yeah, that's poorly written. I wrote this a bit hurriedly before heading out the door before holiday break, so it's not really what I meant to say. Let me rewrite it.

**Comment by kevincwells** [comment]
Implemented in #167
