### ISSUE TITLE
mixin error cannot find bundle in local or upstream bundles

### ISSUE THREAD

**Issue by NANASHI0X74** [clearlinux/mixer-tools#577]
I tried to add a custom mixin bundle just now, but accidentally screwed up the naming. since there was aparently no mixin package remove command or similar, I just deleted the directory in /usr/share/mix/local-bundles. Unfortunately that seems to  have broken mixin completely, when I try to mixin package add now it always gives me the error cannot find bundle in local or upstream bundles. How can I fix that and what's the proper way to remove a local bundle?

**Comment by rchiossi** [comment]
Did you migrate to the mix already?
If you could provide a breakdown of the commands that you ran before the problem happened it would be a plus.

**Comment by NANASHI0X74** [comment]
up to the point where I wanted to remove my own bundle, I followed the tutorial on https://clearlinux.org/documentation/clear-linux/guides/maintenance/mixin, so it was basically this:
`
mkdir ~/mixin-repo
cp -r ~/clearlinux/packages/[PACKAGE]/rpms ~/mixin-repo
sudo mixin repo add mylocalrepo file://$HOME/mixin-repo/
`
then I accidentally mislabeled the bundle:
`
sudo mixin package add [PACKAGE] --bundle -
`
I didn't know how else to remove it, so I just did

`
rm -rf  /usr/share/mix/local-bundles/-
`

subsequent attempts to use mixin package add resulted in the error.

I've since tried to remove the mylocalrepo and local repos with mixin repo remove, but I still get the same error

**Comment by NANASHI0X74** [comment]
I didn't run swupd update --migrate

**Comment by rchiossi** [comment]
Try to edit the file `/usr/share/mix/mixbundles` and remove ` - ` from the list. 
Another alternative is to just create an empty `/usr/share/mix/local-bundles/-` file.

The reason why `package remove` does not exist is mostly because if you just remove it after you migrated to the mix, there would be left over files in your system, so it is better to just revert back using `swupd verify`. Unfortunately this situation with the typo is not covered by mixin at the moment and requires manual fixing as described.

**Comment by rchiossi** [comment]
Also note that `/usr/share/mix` is a `mixer` workspace, so you can run `mixer` in that directory for further functionality.

**Comment by NANASHI0X74** [comment]
thanks, that did fix it
