### ISSUE TITLE
Performance feature: Parallelize manifest subtraction

### ISSUE THREAD

**Issue by gtkramer** [clearlinux/mixer-tools#582]
During the minversion for the bump to format 28 (the +20 build), on a machine with 80 vCPUs from 2 Intel Xeon processors, manifest subtraction took 48 minutes with the machine largely idling for most of the time.

If possible, it would be great if this processing could be parallelized to make better use of machine resources and reduce the time it takes for this step of building the update.  This would help DevOps to scale as more bundle are added.

**Comment by jwakre** [comment]
Also, the file subtraction uses a slice data structure, so its deletion operations take O(n). Using another data structure would allow us to achieve O(1). Maybe we could perform file subtraction during `mixer build bundles` and create the bundle info files with a subtracted file list. `mixer build bundles` stores the files in a map which can perform deletions in O(1).

**Comment by jwakre** [comment]
#586 Resolves this issue

By more carefully creating file records, there is no longer a need to perform file subtraction for bundle manifests. Additionally, manifest file records were generated for all subtracted files which is an expensive operation because it involves file hash calculations. A significant amount of time is saved by not calculating file hashes for files that would have been subtracted.

**Comment by jwakre** [comment]
#586 is merged and working well for DevOps. It seems to improve the speed of typical `mixer build update` commands by ~2.5x. Closing this issue.
