### ISSUE TITLE
Warnings (deprecated commands) originating from swupd

### ISSUE THREAD

**Issue by jurobystricky** [clearlinux/mixer-tools#589]
Running 
<pre>
sudo mixer build image --native
</pre>

I get:
<pre>
Warning: The verify command has been deprecated and will be removed soon.
Please consider using "swupd diagnose" instead.

Warning: The --install option has been deprecated and will be removed soon.
Please consider using "swupd os-install" instead.
</pre>

**Comment by rchiossi** [comment]
This is a warning coming from ister. Since ister is going away in favor of clr-installer, this will go away with it.

On that note, `mixer build image` is just a wrapper, it doesn't really do anything other than call the command to build the image. I suggest trying `clr-installer` directly instead.

https://github.com/clearlinux/clr-installer

**Comment by reaganlo** [comment]
Ister has been replaced with clr-installer. Closing.
