### ISSUE TITLE
Improve performance of rpm extraction

### ISSUE THREAD

**Issue by reaganlo** [clearlinux/mixer-tools#631]
Currently Mixer uses dnf to download and extract rpms. Extracting rpms using dnf is quite slow. 

Research and implement a faster means of rpm extraction such as rpm2cpio or rpm2archive. Also, extract in parallel.

**Comment by yewwayne** [comment]
I'm a little skeptical of the approach taken here.

My hypothesis is that the slow installation is caused by mixer invoking dnf once per bundle (actually twice as it calls [downloadRpms](https://github.com/clearlinux/mixer-tools/commit/58594249745ff775ad2ac2793f641063edea03a8?diff=split#diff-4e3de74fbaeeabc495b046fd277d5fdfL497) first), rather than combining all the bundles' packages into one set and installing them in one dnf invocation.

I compared the 2 approaches in a simple [test](https://gist.github.com/yewwayne/6e08643addb90fad4bbcdc3df4dcc5c9). For a set of 35 bundles and 935 unique packages, the per-bundle dnf install took 26s, whereas the single dnf install took 16s which is identical to extracting the rpms with 4 parallel threads. Note that the test ignores network-related operations by pre-downloading all rpms in advance.
