### ISSUE TITLE
Use "dnf repoquery" to resolve packages in bundles

### ISSUE THREAD

**Issue by yewwayne** [clearlinux/mixer-tools#658]
https://github.com/clearlinux/mixer-tools/blob/8e8fda08c03d03069b2f4b7e99417c1a69ee5c7d/builder/bundles.go#L350

Any particular reason why mixer runs "dnf install --assumeno" and parses the resulting output? The output is formatted for humans,  therefore is likely not stable and not well-suited for scripting.

A more robust alternative would be `dnf repoquery --quiet --queryformat "%{name} %{arch} %{version}-%{release} %{reponame}"`. This directly produces the attributes wanted by packageMetadata in the requested format, e.g. `vim x86_64 8.1.2333-1014 clear`.

**Comment by yewwayne** [comment]
On second thought, I guess the obvious answer to my own question is "to resolve the full set of package dependencies." In that case, `dnf repoquery --requires --recursive --resolve` will recursively list dependencies of the requested target package(s).

**Comment by rchiossi** [comment]
Indeed, we use install to get the dependencies.
If I recall correctly, when this code was first created, we couldn't get that information with repoquery. This is legacy code though, it existed even before the project was ported to Go.

**Comment by phmccarty** [comment]
The reason for using `dnf install --assumeno ...` is because some symbols were (and still are) provided by multiple packages, and for those cases, `dnf repoquery ...` lists all of the providers instead of just one. So, it's not there for legacy reasons, it is there because we wanted mixer (via dnf) to resolve dependencies so that each *Requires* symbol from a package maps to exactly one package that *Provides* that symbol. `dnf install --assumeno ...` satisfied that requirement.

That being said, mixer *could* use the output of `dnf repoquery ...` instead of `dnf install --assumeno ...`. The package listing for a bundle may be a superset of what is needed for any given bundle, but over time, we will reduce the number of packages providing the same symbols. Also, the bundle size increases would be minimal given the current impact, and you get the customizable queryformats with `dnf repoquery ...`.
