### ISSUE TITLE
Question: format bumps since 5.6.0

### ISSUE THREAD

**Issue by aaronovz1** [clearlinux/mixer-tools#687]
I am looking to update mixer and swupd-client, and want to know if there have been any format bumps since 5.6.0, or any other breaking changes I should be aware of.

I am currently running mixer in docker and run the following commands:
```
mixer init --clear-version ${prev_version} --format ${swupd_format} --upstream-url ${content_url_parameter} --no-default-bundles --mix-version ${os_version} --offline"

mixer build update --format ${swupd_format} --min-version ${SWUPD_MIX_MIN_VERSION}
mixer build delta-packs --report --previous-versions ${SWUPD_DELTAPACK_VERSIONS} --to $os_version
mixer build delta-manifests --previous-versions ${SWUPD_DELTAPACK_VERSIONS} --to $os_version
```

**Comment by jwakre** [comment]
> I am looking to update mixer and swupd-client, and want to know if there have been any format bumps since 5.6.0, or any other breaking changes I should be aware of.

Upstream Clear is on format 29. The following are significant changes that occurred after that release and may impact you:
* Deprecated index manifests
* Mixer no longer runs itself inside of a Docker container.
> 
> I am currently running mixer in docker and run the following commands:

Since Mixer no longer runs itself inside of a Docker container, it will run on your host. If your host does not have the required packages to run Mixer, the package dependencies must be added or Mixer could be executed within a container that satisfies its dependencies.
> 
> ```
> mixer init --clear-version ${prev_version} --format ${swupd_format} --upstream-url ${content_url_parameter} --no-default-bundles --mix-version ${os_version} --offline"
> 
> mixer build update --format ${swupd_format} --min-version ${SWUPD_MIX_MIN_VERSION}
> mixer build delta-packs --report --previous-versions ${SWUPD_DELTAPACK_VERSIONS} --to $os_version
> mixer build delta-manifests --previous-versions ${SWUPD_DELTAPACK_VERSIONS} --to $os_version
> ```

**Comment by aaronovz1** [comment]
Ok. So I am using mixer as part of Yocto (meta-swupd), so my format numbers are different. I'll assume from you've said that in order to upgrade mixer/swupd-client I need to increment my format version.

For docker, I have been using https://github.com/clearlinux/dockerfiles/tree/master/clr-sdk - should this still be ok?

**Comment by jwakre** [comment]
> Ok. So I am using mixer as part of Yocto (meta-swupd), so my format numbers are different. I'll assume from you've said that in order to upgrade mixer/swupd-client I need to increment my format version.

Are you a downstream mix of Clear or are you maintaining your own upstream?
> 
> For docker, I have been using https://github.com/clearlinux/dockerfiles/tree/master/clr-sdk - should this still be ok?

Yes, using a Clear Docker container will resolve package dependencies for Mixer. To update the version of Mixer, you will need to update the version of Clear in the container so that the dependencies will get updated too.

**Comment by aaronovz1** [comment]
I am maintaining our own non-clearlinux upstream. Looks like a format bump is required. Thanks.

**Comment by jwakre** [comment]
Yes, you will need a format bump. Also, you will need to be aware of the also-add feature that was added in v5.8.0. Updating swupd/mixer may require coordination around this feature.

**Comment by aaronovz1** [comment]
I am currently running swupd-client 3.19. I was going to bump that to 3.23.1 and make the required compatibility changes in the rest of our system at the same time I bumped the format and OS version.
