### ISSUE TITLE
Support feeding mixer using chroot-defined-bundle directory

### ISSUE THREAD

**Issue by mrkz** [clearlinux/mixer-tools#7]
This way a mixer user could define what gets added/removed/modified from a bundle by changing directly the chroot directory for the given bundle to mix.

A simple use case for this would be as follows:
- User wants to add X binary into `new-bundle` bundle.

The flow for this today implies packaging the binary into an RPM format and create a repo so mixer can consume it and modify the bundle definition to specify that new RPM will be part of that bundle.

With this feature, user only would need to copy the proper binary/files in the chroot directory defined for `new-bundle` and then the mixer would detect new files in the bundle, removing entirely the RPM management from the user perspective.

So in the case  `new-bundle` contains the following structure:

```
./new-bundle/
├── bin -> usr/bin
├── lib -> usr/lib
├── lib64 -> usr/lib64
├── sbin -> usr/sbin
└── usr
    └── bin
        └── bash
```

and user wants to add new file (e.g: `/usr/bin/cowsay`) the new chroot for `new-bundle` would be like:

```
./new-bundle/
├── bin -> usr/bin
├── lib -> usr/lib
├── lib64 -> usr/lib64
├── sbin -> usr/sbin
└── usr
    └── bin
        ├── bash
        └── cowsay
```

Then user could execute the mixer to create new update/mix and it would take the previously defined chroot.

**Comment by tmarcu** [comment]
This is already possible with mixer as the update creator has no idea or care about *how* the chroots were created. Certain files are inserted in the chroot(s) that are not part of any RPM package, i.e, the root update certificate, during update creation. However in the general case, because mixer is intended to be used to add and generate update content in a distro friendly way, we have the bundle-chroot-builder that takes RPMs and outputs chroots for us automatically.

You can indeed generate one or many chroots manually and administrate them yourself as you see fit still.

**Comment by phmccarty** [comment]
Perhaps we should document how to create chroots manually when using mixer?
